import {Post} from './postTypes';

export const postListMock: Post[] = [
    {
      id: '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed',
      description: 'Este é o meu primeiro post!',
      title: 'Um novo começo nas redes sociais.',
      author: {
        profileURL: 'https://i.imgur.com/YeE3yKf.jpg',
        name: 'John Doe',
        userName: 'johndoe',
      },
      imageURL: 'https://i.imgur.com/VyfuWYa.jpg',
      reactionCount: 10,
      commentCount: 5,
      favoriteCount: 2,
    },
    {
      id: 'e2c56db5-67f1-44ab-94a3-9877efdc76a4',
      description: 'Confira esta foto incrível!',
      title: 'Uma foto que merece ser vista.',
      author: {
        profileURL: 'https://i.imgur.com/BrJUnRl.jpg',
        name: 'Jane Smith',
        userName: 'janesmith',
      },
      imageURL: 'https://i.imgur.com/KkcrB5y.jpg',
      reactionCount: 15,
      commentCount: 8,
      favoriteCount: 3,
    },
    {
      id: '3f251f7d-a6e8-4823-bc9b-97d0356d1dcf',
      description: 'Acabei de terminar de ler este livro e é incrível!',
      title: 'Uma leitura que vale a pena.',
      author: {
        profileURL: 'https://i.imgur.com/BxgHDci.jpg',
        name: 'Mark Johnson',
        userName: 'markjohnson',
      },
      imageURL: 'https://i.imgur.com/NdrA2BY.jpg',
      reactionCount: 20,
      commentCount: 12,
      favoriteCount: 5,
    },
    {
      id: '8aa14f92-af48-4f3a-897c-ec569d25bb30',
      description: 'Não posso acreditar que já é maio!',
      title: 'O tempo voa!',
      author: {
        profileURL: 'https://i.imgur.com/FmSbPv3.jpg',
        name: 'Amy Lee',
        userName: 'amylee',
      },
      imageURL: 'https://i.imgur.com/vkscdqk.jpg',
      reactionCount: 5,
      commentCount: 3,
      favoriteCount: 1,
    },
    {
      id: '6927c54e-df67-4fc0-a0ef-14d5ab6de58d',
      description: 'Dia de codificação!',
      title: 'Tempo para programar!',
      author: {
        profileURL: 'https://i.imgur.com/DF4Jfxq.jpg',
        name: 'Santiago Emilio',
        userName: 'sanemilio',
      },
      imageURL: 'https://i.imgur.com/rsOe2hC.jpg',
      reactionCount: 0,
      commentCount: 0,
      favoriteCount: 0,
    },
    {
      id: 'bd8de917-b256-402e-94fc-eb6ef1700a85',
      description: 'Qual é a sua cor favorita?',
      title: 'Vamos falar sobre preferências.',
      author: {
        profileURL: 'https://i.imgur.com/YeE3yKf.jpg',
        name: 'John Doe',
        userName: 'johndoe',
      },
      imageURL: 'https://i.imgur.com/zx94i19.jpg',
      reactionCount: 2,
      commentCount: 1,
      favoriteCount: 0,
    },
    {
      id: '7b3b6e3d-14e2-4876-baf5-aeaed7b8a5ee',
      description: 'Estou tão animado para o fim de semana!',
      title: 'Hora de aproveitar!',
      author: {
        profileURL: 'https://i.imgur.com/BrJUnRl.jpg',
        name: 'Jane Smith',
        userName: 'janesmith',
      },
      imageURL: 'https://i.imgur.com/LWopzZH.jpg',
      reactionCount: 8,
      commentCount: 4,
      favoriteCount: 1,
    },
    {
      id: '15b13005-8494-45d4-85e7-cbdf1aa5bc7d',
      description: 'Acabei de voltar das férias e foi incrível!',
      title: 'Momentos inesquecíveis!',
      author: {
        profileURL: 'https://i.imgur.com/BxgHDci.jpg',
        name: 'Mark Johnson',
        userName: 'markjohnson',
      },
      imageURL: 'https://i.imgur.com/WZZLeHg.jpg',
      reactionCount: 25,
      commentCount: 10,
      favoriteCount: 4,
    },
    {
      id: 'e3f6fe02-91e5-42a1-a8b2-62b29b2f3777',
      description: 'Estou adorando este novo restaurante!',
      title: 'Descoberta gastronômica!',
      imageURL: 'https://i.imgur.com/FmSbPv3.jpg',
      author: {
        profileURL: 'https://i.imgur.com/OGQRFok.jpg',
        name: 'Amy Lee',
        userName: 'amylee',
      },
      reactionCount: 35,
      commentCount: 0,
      favoriteCount: 0,
    },
];
  